services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_KRAFT_CLUSTER_ID: "kraft-cluster-1"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CFG_LOG_DIRS: "/bitnami/kafka/data"
    volumes:
      - kafka_data:/bitnami/kafka/data

  postgres:
    build: ./postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command:
      [
        "postgres",
        "-c",
        "wal_level=logical",
        "-c",
        "max_replication_slots=4",
        "-c",
        "max_wal_senders=4",
      ]

  connect:
    image: quay.io/debezium/connect:2.3
    container_name: connect
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - postgres
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
    volumes:
      - connect-configs:/kafka/connect/configs 

  register-connector:
    image: curlimages/curl:latest
    depends_on:
      - connect
    volumes:
      - ./debezium/register-connector.sh:/register-connector.sh
      - ./debezium/register-postgres.json:/config/register-postgres.json
    entrypoint: ["sh", "/register-connector.sh"]

  kafka-consumer:
    build: ./kafka-consumer
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: testdb_cdc.public.member
    ports:
      - "5000:5000"

  airflow-webserver:
    build: ./airflow
    restart: always
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:secretpassword@postgres/testdb
      AIRFLOW__CORE__FERNET_KEY: "7r4em_XyS2IMUhwlmJ5NjsNG7mHewDZL4xDJA6CCN68="
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__DEFAULT_USER: airflow
      AIRFLOW__WEBSERVER__DEFAULT_PASSWORD: airflow
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
      AIRFLOW__WEBSERVER__SECRET_KEY: "e3xFGTPd-W3jYrU4mMKhx6JxT1o3pQM1gpk5OjLyJVo"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: >
      bash -c "
        airflow db migrate &&
        airflow users create --username airflow --password airflow --firstname Air --lastname Flow --role Admin --email admin@example.com &&
        airflow webserver
      "

  airflow-scheduler:
    build: ./airflow
    restart: always
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:secretpassword@postgres/testdb
      AIRFLOW__CORE__FERNET_KEY: "7r4em_XyS2IMUhwlmJ5NjsNG7mHewDZL4xDJA6CCN68="
      AIRFLOW__WEBSERVER__SECRET_KEY: "e3xFGTPd-W3jYrU4mMKhx6JxT1o3pQM1gpk5OjLyJVo"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    command: ["scheduler"]

  search:
    build: ./search
    container_name: search
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: secretpassword
      DB_NAME: testdb
      DB_PORT: 5432

volumes:
  kafka_data:
  pgdata:
  connect-configs:
